stages: # List of stages for jobs, and their order of execution
    - test

before_script:
    # Install composer dependencies
    - wget https://composer.github.io/installer.sig -O - -q | tr -d '\n' > installer.sig
    - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
    - php -r "if (hash_file('SHA384', 'composer-setup.php') === file_get_contents('installer.sig')) { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
    - php composer-setup.php
    - php -r "unlink('composer-setup.php'); unlink('installer.sig');"

php8.2:
    image: php:8.2
    stage: test
    script:
        - php composer.phar install
        - phpunit --configuration phpunit.xml.dist

php8.3:
    image: php:8.3
    stage: test
    script:
        - php composer.phar install
        - phpunit --configuration phpunit.xml.dist

php8.4:
    image: php:8.4
    stage: test
    script:
        - php composer.phar install
        - phpunit --configuration phpunit.xml.dist