services:
  php8.1:
    image: php:8.1-cli-alpine
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      PHP_IDE_CONFIG: "serverName=PhpCodingStandard"
      SYMFONY_DEPRECATIONS_HELPER: disabled
    working_dir: /app
    volumes:
      - .:/app
    user: 1000:1000

  php8.2:
    image: php:8.2-cli-alpine
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      PHP_IDE_CONFIG: "serverName=PhpCodingStandard"
      SYMFONY_DEPRECATIONS_HELPER: disabled
    working_dir: /app
    volumes:
      - .:/app
    user: 1000:1000

  php8.3:
    image: php:8.3-cli-alpine
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      PHP_IDE_CONFIG: "serverName=PhpCodingStandard"
      SYMFONY_DEPRECATIONS_HELPER: disabled
    working_dir: /app
    volumes:
      - .:/app
    user: 1000:1000

  php8.4:
    image: php:8.4-cli-alpine
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      PHP_IDE_CONFIG: "serverName=PhpCodingStandard"
      SYMFONY_DEPRECATIONS_HELPER: disabled
    working_dir: /app
    volumes:
      - .:/app
    user: 1000:1000

  php8.5:
      image: php:8.5-cli-alpine
      extra_hosts:
          - "host.docker.internal:host-gateway"
      environment:
          PHP_IDE_CONFIG: "serverName=PhpCodingStandard"
          SYMFONY_DEPRECATIONS_HELPER: disabled
      working_dir: /app
      volumes:
          - .:/app
      user: 1000:1000
