services:
  php8.1:
    command:
      - tail
      - -f
      - /dev/null
    image: php:8.1-cli-alpine
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      PHP_IDE_CONFIG: "serverName=PhpCodingStandard"
      SYMFONY_DEPRECATIONS_HELPER: disabled
    working_dir: /app
    volumes:
      - .:/app
    user: 1000:1000

  php8.2:
    command:
      - tail
      - -f
      - /dev/null
    image: php:8.2-cli-alpine
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      PHP_IDE_CONFIG: "serverName=PhpCodingStandard"
      SYMFONY_DEPRECATIONS_HELPER: disabled
    working_dir: /app
    volumes:
      - .:/app
    user: 1000:1000

  php8.3:
    command:
      - tail
      - -f
      - /dev/null
    image: php:8.3-cli-alpine
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      PHP_IDE_CONFIG: "serverName=PhpCodingStandard"
      SYMFONY_DEPRECATIONS_HELPER: disabled
    working_dir: /app
    volumes:
      - .:/app
    user: 1000:1000

  php8.4:
    command:
      - tail
      - -f
      - /dev/null
    image: php:8.4-cli-alpine
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      PHP_CS_FIXER_IGNORE_ENV: '1'
      PHP_IDE_CONFIG: "serverName=PhpCodingStandard"
      SYMFONY_DEPRECATIONS_HELPER: disabled
    working_dir: /app
    volumes:
      - .:/app
    user: 1000:1000
