version: '3.2'

services:
  php:
    container_name: cs_container
    command:
      - tail
      - -f 
      - /dev/null
    image: composer:latest
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      PHP_IDE_CONFIG: "serverName=PhpCodingStandard"
      SYMFONY_DEPRECATIONS_HELPER: disabled
    volumes:
      - .:/app
      - ~/.composer:/home/application/.composer
    user: 1000:1000
