version: '3.5'

networks:
    app-network:
        driver: bridge

services:

    workspace:
        image: algoritmasw/development:8.3-node-20.10-composer-2-xdebug
        environment:
            - SSH_AUTH_SOCK=${SSH_AUTH_SOCK}
            - PHP_MEMORY_LIMIT=4G
        extra_hosts:
            - host.docker.internal:host-gateway
        volumes:
            - .:/app
            - ${SSH_AUTH_SOCK}:${SSH_AUTH_SOCK}
        networks:
            - app-network