types:
  - feature
  - feat
  - fix
  - docs
  - refactor
  - performance

categories:
  feat: Features
  feature: Features
  fix: Bug fixes
  docs: Documentation
  refactor: Refactor
  performance: Performance improvements

template: |
  {% if categories %}
  {% each categories %}
  ### {{ title }}

  {% each entries %}
  - [{{ title }}]({{ commit.web_url }})\
  {% if author.credit %} by {{ author.reference }}{% end %}

  {% end %}

  {% end %}
  {% else %}
  No changes.
  {% end %}
